{% set name = "csvkit" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 311f21787615a91656897e217c62ab26c8446d67309b61bd013e345b35816fdf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - csvclean = csvkit.utilities.csvclean:launch_new_instance
    - csvcut = csvkit.utilities.csvcut:launch_new_instance
    - csvformat = csvkit.utilities.csvformat:launch_new_instance
    - csvgrep = csvkit.utilities.csvgrep:launch_new_instance
    - csvjoin = csvkit.utilities.csvjoin:launch_new_instance
    - csvjson = csvkit.utilities.csvjson:launch_new_instance
    - csvlook = csvkit.utilities.csvlook:launch_new_instance
    - csvpy = csvkit.utilities.csvpy:launch_new_instance
    - csvsort = csvkit.utilities.csvsort:launch_new_instance
    - csvsql = csvkit.utilities.csvsql:launch_new_instance
    - csvstack = csvkit.utilities.csvstack:launch_new_instance
    - csvstat = csvkit.utilities.csvstat:launch_new_instance
    - in2csv = csvkit.utilities.in2csv:launch_new_instance
    - sql2csv = csvkit.utilities.sql2csv:launch_new_instance

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - agate >=1.6.2
    - agate-excel >=0.2.1
    - agate-dbf >=0.2.0
    - agate-sql >=0.5.2
    - six >=1.6.1

test:
  imports:
    - csvkit
    - csvkit.convert
    - csvkit.utilities
  commands:
    - csvclean --help
    - csvcut --help
    - csvformat --help
    - csvgrep --help
    - csvjoin --help
    - csvjson --help
    - csvlook --help
    - csvpy --help
    - csvsort --help
    - csvsql --help
    - csvstack --help
    - csvstat --help
    - in2csv --help
    - sql2csv --help
    - pip check
  requires:
    - pip

about:
  home: https://csvkit.rtfd.org/
  license_file: COPYING
  license: MIT
  license_family: MIT
  summary: A suite of command-line tools for working with CSV, the king of tabular file formats
  dev_url: https://github.com/wireservice/csvkit
  doc_url: https://csvkit.rtfd.org/

extra:
  recipe-maintainers:
    - jan-janssen
