travis:
  secure:
    BINSTAR_TOKEN: wKRBsSlwXBRXu5gr0xMtET++Sf5wulHB8cRGPObK7At/CAwGoCPUYk+JNLNOePtN/2Lrg7Z0xP3tq4Jsn4Iifb41iGsqveWeazdGToLb2s1gWWjPRXNJhwYXfFFVyDthJTuwVw33ChSSvoYNUtfOr2S5fdUzypU5UnLIBvRO2OL7mJ6WD8Z4dqnDxRIQVErzOCmfmQJFZUm2+pr5z+9mbfmYqNFyrEIZz4uaxLtNywzpCwUpBbLpJWyv5s/oVdihC9NLSKKPzz9boBod34pIXMIhgACHnfioTwVnXdYRSdzBsZDFWGvV6m/G7DYDiNHRHljATrWdAgg0HcvlFQ5kmMtB46GhSqFepkSQwC7zrCykUzj6IHm4kZl4Lfb5pYZqpcNI6xib6SYq+vlIOROqMLtLwnXaF9ivJTkcCJeAm//badKNwDN/h74qEqoj7OSRSzWeom2zkCTa2G4ux2U44IY4pQPHjqiEwIHWNpTbNfUIIn/kP7DnzTif0fuZYdmr4R9vgGIprhNg8hLDR42LewLZ8Z6xB/PEK9DFdQu4FV22pDD0PDlqYDp6F90P2AMmskACLZYs39cLVY5akxFKAxzwnTIWmgx2TeGZ37qeEOWyB4dNHbxFfwud1sWkOskHiXON0+useQWqWEHlR+bF2hOq753D2X935N4lf4kaOaA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
